export const API_CALL_BEGAN = "API_CALL_BEGAN";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const AUTH_REQUESTED = "AUTH_REQUESTED";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOAD_USER = "AUTH_LOAD_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CELL_GROUPS_REQUESTED = "CELL_GROUPS_REQUESTED";
export const CELL_GROUP_ERROR = "CELL_GROUP_ERROR";
export const GET_CELL_GROUPS_SUCCESS = "GET_CELL_GROUPS_SUCCESS";
export const GET_CURRENT_USER_CELL_GROUPS_SUCCESS =
  "GET_CURRENT_USER_CELL_GROUPS_SUCCESS";
export const CREATE_CELL_GROUP_SUCCESS = "CREATE_CELL_GROUP_SUCCESS";
export const UPDATE_CELL_GROUP_SUCCESS = "UPDATE_CELL_GROUP_SUCCESS";
export const DELETE_CELL_GROUP_SUCCESS = "DELETE_CELL_GROUP_SUCCESS";
export const ADD_CELL_GROUP_MEMBER = "ADD_CELL_GROUP_MEMBER";
export const DELETE_CELL_GROUP_MEMBER = "DELETE_CELL_GROUP_MEMBER";
export const CLEAR_USER_CELLGROUP = "CLEAR_USER_CELLGROUP";

export const PROFILE_REQUESTED = "PROFILE_REQUESTED";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const SAVE_PROFILE_SUCCESS = "SAVE_PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const USER_REQUESTED = "USER_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

export const MEMBERS_REQUESTED = "MEMBERS_REQUESTED";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const MEMBERS_ERROR = "MEMBERS_ERROR";
export const CLEAR_USER_MEMBERS = "CLEAR_USER_MEMBERS";
